### ISSUE TITLE
Issue while trying to run custom anomoly detection algoritham using path 1

### ISSUE THREAD

**Issue by AMK13** [numenta/NAB#368]
Hi, I am facing an issue when trying to run my detector using "python run.py -d pyod" where pyod is the detector I am trying to use. 

I get the following error, any feedback on how to proceed will be helpful. 

Proceed? (y/n): y
Traceback (most recent call last):
  File "run.py", line 202, in <module>
    main(args)
  File "run.py", line 68, in main
    detectorConstructors = getDetectorClassConstructors(args.detectors)
  File "run.py", line 41, in getDetectorClassConstructors
    d : globals()[detectorNameToClass(d)] for d in detectors}
  File "run.py", line 41, in <dictcomp>
    d : globals()[detectorNameToClass(d)] for d in detectors}
KeyError: 'PyodDetector'

Best wishes

Muneeb

**Comment by lscheinkman** [comment]
You need to import your detector from `run.py`. 
```
from nab.detectors.pyod import PyodDetector`
```
